baseURL = 'https://r4.dk/'
languageCode = 'en-us'
title = '0xlime Blog'
buildDrafts = true


[module]
[[module.imports]]
path = "github.com/tomfran/typo"


[taxonomies]
tag = 'tags'

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
  enableCustomCSS = true
# Meta description
description = "Security Research and Bug Hunting"


# Appearance settings
colorPalette = 'default'
theme = 'light'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Welcome to 0xlime Blog!'
homeIntroContent = """
My name is Emil Hørning and I am a security researcher and bug bounty hunter! I also work as the Head of Hackers at [Defend Denmark](https://defenddenmark.dk/).
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Author information
author = "0xlime"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/0xlime"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/emil-h%C3%B8rning-8824641b4/"

[[params.social]]
name = "link"
url = "https://r4.dk"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "presentations"
url = "/presentations"

[[params.menu]]
name = "about"
url = "https://r4.dk"

# Syntax highlight on code blocks
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"  # Dark background with vibrant colors
    guessSyntax = true
    noClasses = true  # Keep true to force the inline styles
    tabWidth = 2




